os:
  - linux

dist: trusty

language: node_js

node_js:
  - lts/*

env:
  - MOZ_HEADLESS=1

addons:
  chrome: stable
  firefox: latest

script:
  - npm run lint
  - npm run test
  - npm run test-e2e ChromeHeadlessNoSandbox,FirefoxHeadless
